[tool.poetry]
name = "pm3-easy-standalone"
version = "0.1.0"
description = ""
authors = ["william <william@le-roux.ovh>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
